cache:
  directories:
    - /home/travis/virtualenv
install:
  - sudo -H pip install flake8
  - sudo -H ./setup.sh | awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }'

script:
  - flake8 --select=F inbox
  - pylint -d all -e w0631 inbox
  - NYLAS_ENV=test py.test inbox/test -m "not networkrequired"
